version: "3.3"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - pgsql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html:delegated
  pgsql:
    image: postgres:12.11
    ports:
      - "5432:5432"
    env_file:
      - ./pgsql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - .:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:16
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - .:/var/www/html

